### ISSUE TITLE
Impossible to open xlsx create from Excel

### ISSUE THREAD

**Issue by FabPari** [rabanti-github/NanoXLSX#29] opened 2022-09-08 16:36 UTC
Hi dear, If I try to create new empty xlsx file from Excel and after load with Nanoxlsx it It work
`Workbook wb = Workbook.Load("Test.xlsx");`
If I update the file and write something with excel and I try to load I receive this error
InnerException = {"The XML entry could not be read from the input stream. Please see the inner exception:"}

In conclusion impossible to update file from excel and after load from Nanoxlsx

My excel version : Microsoft® Excel® 2021 MSO (Version 2207 Build 16.0.15427.20182) 64 bit 

Thanks for support
Fabio

**Comment by rabanti-github** [comment] 2022-09-08 23:20
Hi
Thank you for the report. I am sorry, I have earlier written a response, but it looks like I have not submitted it.

Can you provide me an Excel file that causes the crash, when trying to read it with the library? You can add it as attachment.
Thank you in advance.

**Comment by FabPari** [comment] 2022-09-09 06:23
Hi Dear
Thanks too much for your reply
[Test.xlsx](https://github.com/rabanti-github/NanoXLSX/files/9532836/Test.xlsx)

Attached test file create with Nanoxlsx  and modified by Excel impossible to load
thanks
Fabio

**Comment by rabanti-github** [comment] 2022-09-09 07:32
Hi
Thank you for the test file.
However, I could not reproduce the problem. I could read all data without a crash, when loading the file with NanoXLSX.

I need some more information:
- Used version of NanoXLSX (Have you tried with the new **2.0.0 version**, published last Saturday?)
- Steps to reproduce (maybe I am missing something. I just have used the Workbook.Load function to check)
- If the steps are too complicates: a code snippet
- If available, but not mandatory: a stacktrace to see, in which reader function the problem emerges

Thank you in advance

**Comment by FabPari** [comment] 2022-09-09 07:55
Hi Dear
thanks too much for you reply.
Unfurtunately I install NanoXLSX  v.2.0.0 but loading this file I receive the error:
"The XML entry could not be read from the input stream. Please see the inner exception:"
I really don't understand what am I doing wrong.
I reply to your question

1. Used version v.2.0.0
2. Debug this code line with my file give me the error: _Workbook wb = Workbook.Load("Test.xlsx");_ 

Stack trace:   at NanoXLSX.LowLevel.XlsxReader.Read()
   at NanoXLSX.Workbook.Load(String filename, ImportOptions options)
   at ProductImport.Program.<EsportaInExcelPerTraduzioni>d__1.MoveNext() in C:\XXXX\Program.cs:line 162

After this I make another test.
Empty c# consolle solution (attached here) 
Inside Debug file I copy myTest.xlsx file
[TestNanoXLSX.zip](https://github.com/rabanti-github/NanoXLSX/files/9533445/TestNanoXLSX.zip)

**Remove try catch**
Try to debug and load file give me this error : : The passed column width is out of range (0 to 255)

![image](https://user-images.githubusercontent.com/66635441/189300104-38d92fef-bf9a-44ee-921b-cf0130abd0ad.png)


I hope this can help to find solution

Thanks a lot for your support
Fabio

**Comment by rabanti-github** [comment] 2022-09-09 08:07
Hi
Thank you for the additional information.
I have a guess: Could it be that you try to read the file, if it is still open in Excel?
Excel is notorious for disallowing streams even in read-only mode, if a file is open.
In my case, only an error occurred, when I had the file opened in Excel at the same time.

If Excel is open, please close the file and try again. If it is still not working, I have to do an in-depth analysis.

Thank you in advance.

**Comment by FabPari** [comment] 2022-09-09 14:47
No Excel is closed : the error is :The passed column width is out of range (0 to 255)
I think isn't and Excel problem.
I think that, when Excel save the file modify something that create the error.
What about column width out of range

Fabio

**Comment by rabanti-github** [comment] 2022-09-09 16:28
Hi,
I have to check the xml structure of your file, when I am back at home. The strange thing is that I can read your file with your sample program. And the specs should not have changed. I hopefully can report back tonight

**Comment by rabanti-github** [comment] 2022-09-09 16:30
A quick question: What is your System's locale? Is it different than 'en-US'?

**Comment by FabPari** [comment] 2022-09-09 16:48
Yes is locate in Italian language
Fabio

Il ven 9 set 2022, 18:31 Raphael Stoeckli ***@***.***> ha
scritto:

**Comment by rabanti-github** [comment] 2022-09-09 23:17
Hi,
I could probably figure out the problem. It looks like the system localization is the issue. The Italian decimal separator is "," (comma), whereas the US / neutral separator is "." (point). I was not enough careful in the reader, as it looks.
However, In my testes, I could not really set my system to the Italian locale. The override was ignored.
But I made a possible fix.
Could you please test the attached project? It contains a patched NanoXLSX-DLL file (in folder lib) instead of the NuGet dependency. See the attachment in this post.
If this DLL works for you, I will release a patch ASAP.
Thank you in advance.
[TestNanoXLSX_mod.zip](https://github.com/rabanti-github/NanoXLSX/files/9539166/TestNanoXLSX_mod.zip)

**Comment by FabPari** [comment] 2022-09-10 08:31
You are mi god!!!!! :-)
Fantastic it work!!!!!! thanks a lot
Fabio

**Comment by rabanti-github** [comment] 2022-09-10 09:51
OK, thanks. I will release a patch version today

**Comment by rabanti-github** [comment] 2022-09-10 20:58
Hi,
The issue is fixed with the release v2.0.1.
The NuGet package should be available in some minutes.

Thank you again for the report and for testing the fix.

**Comment by FabPari** [comment] 2022-09-10 21:27
Tnks too much for your support!
Fabio

Il sab 10 set 2022, 22:58 Raphael Stoeckli ***@***.***> ha
scritto:

**Comment by rabanti-github** [comment] 2022-09-29 20:49
I will close this issue for now.
Please reopen or file a new one, if something is not working as expected.
Thanks again for the report.

**Closed by rabanti-github** 2022-09-29 20:49 UTC
Labels: bug
