### ISSUE TITLE
The xlsx format breaks when i use nanoxlsx to write "EMPTY_STRING" to a cell.

### ISSUE THREAD

**Issue by Leonetienne** [rabanti-github/NanoXLSX#1] opened 2019-11-29 20:24 UTC
So i was using nanoxlsx to save my item database to an xlsx sheet. I escaped empty strings with "EMPTY_STRING", so that the cell wouldn't be empty.

Note that i did not try to write the quotation marks. The string i tried to save was EMPTY_STRING

When i tried reading one of these EMPTY_STRING Cells i would just get the value of another random cell instead.

When investigating the xlsx file via Excel, i found that these cells would in fact not contain the string "EMPTY_STRING" but "EMPTY_STRING]". Note the extra ']'. 
I would venture that this bracket belongs in the xml code and is now missing there messing up the parsing.

I solved the issue by just changing my escape string form "EMPTY_STRING" to "(EMPTY_STRING)".

**Comment by Leonetienne** [comment] 2019-11-29 20:30
By the way, massive thanks for making this awesome excel lib

**Comment by rabanti-github** [comment] 2019-11-29 23:44
Hi,
Can you provide the code where you write the value "EMPTY_STRING"? Currently, I cannot reproduce 
this issue.
`workbook.CurrentWorksheet.AddNextCell("EMPTY_STRING");` does not produce such an error in my environment.
And there should also be no instance of a bracket in the generated XML. Furthermore, EMPTY_STRING is also no "magic number" in the library that could be misinterpreted. This is really odd. 

Some intermediate approaches to solve the problem beside your mentioned workaround:
- Have you referenced the latest version of NanoXLSX --> v1.3.3 (or PixoXLSX --> v2.6.4)?
- Have you tried to use something like `workbook.CurrentWorksheet.AddNextCell("");`? --> It defines a cell with an empty value (maybe I have misunderstood your intention)
- Have you tried a completely other placeholder like "---" or "X"?

Would be great, if you could provide some sample code and maybe one of the corrupted Excel files.
Thank you in advance.

Greetings,
Raphael

**Comment by Leonetienne** [comment] 2019-11-30 01:29
My first version just did exactly this: `workbook.CurrentWorksheet.AddNextCell("");`, because i did just not escape empty strings at all.
However `foreach (KeyValuePair<string, Cell> cell in workbook.CurrentWorksheet.Cells)` seemed to just skip empty scells, so i escaped them.   (Eg, if B2 would be empty `cell.Value.Value` would return the value of C2, even though `cell.Key` would be "B2").

Don't call me crazy just yet haha
In my disbelieve in reality literally had every cell iterate one at a time and had printed out the column, row, key and value for every single cell. Column = 2; Row = 1; Key = "C2" and printed the value of D2

I would gladly provide some source.
Here is how i create the xlsx file:
https://pastebin.com/FLz5Md5c

And here is how i read it:
https://pastebin.com/kRY0hYuV

It might be important to mention that my database is pretty large. The xlsx file can get up to 115000 rows long (about 20mb)

I am now encountering a new issue while reading where <1% of the rows of my database (still multiple hundred) are shifted. Eg `cell.Value.columnNumer` is 17 but it returns the value of column 7 of an entirely different row. (Kinda bad when my iconPath suddenly becomes "Use: Heals 200hp".

When looking at the sheet in excel the cells are not misplaced.

Even better, when i place the "faulty rows" in a much much smaller xlsx (only a couple hundred rows long)
they get read in fine.




Regarding this, i would also like to provide the xlsx file in question.
Here is my generated xlsx file in two variants.
Variant one is with empty cells and variant two is with escaped empty cells.
https://sharefiles.app/download/04e1f0a1965d32cda17b9ae54aa05d04b7ebe9e2

Sadly this link will expire after 24hrs, just hit me up if you want a new one

If you'd like i would be willing to share the entire project folders.

But the project creating the xlsx is nothing but a program that parses a large dump file (the parser is thourugly tested), removes duplicates and then saves it as an xlsx. These xlsx's look correct in excel.

The reader already fails at re-loading that same List<Item> into memory from the xlsx. So there would be little point in sharing the whole project. Keep in mind, i only get a couple hundred faulty rows out of my 150000 row long database.


Sorry for the long wait, it takes quite a while to compile these dumpfiles into xlsx since they are quite large and have lots of duplicate entries.

**Comment by rabanti-github** [comment] 2019-11-30 01:56
Thank you for the additional information.
I downloaded the files from sharefiles.app, so it's no problem about the 24h (sehe ich da etwa deutsche MMO Daten :-P ?). And pastebin should be persistent.
However, it is extremely late or early here, respectively. And I have an appointment today.
Please give me some hours to look into this.

It could be possible that the reader is buggy (is still beta) not the writer, since all my previous tests were relying on the writer only. I can say more after the analysis.
Can you confirm in the meantime, that you use the most recent version of NanoXLSX from NuGet or sources?

Thank you,
Raphael

**Comment by Leonetienne** [comment] 2019-11-30 03:32
Sure, take your time.

Just checked NanoXLSX\\AssemblyInfo.cs and it appears to be version 1.3.3

Haha yes, this just _may_ be a german mmo item database^^

**Comment by rabanti-github** [comment] 2019-11-30 23:54
I think I can reproduce the issue now. I could track it down to the reader. The writer seems OK.  It may have something to do with the newlines in the description texts, but this should be no problem to handle, since valid (as far as I know). Nevertheless, a very strange bug.

 --> **Still Investigating**

Iwill inform you, as soon as fixed, or is more information is necessary. You find intermediate fixes in the dev branch.

**Comment by Leonetienne** [comment] 2019-12-01 09:50
Thanks, glad you can reproduce it.
Things always work until some lunatic decides to do something no one has ever thought someone would ever do, like multiple lines per cell haha

**Comment by rabanti-github** [comment] 2019-12-01 16:21
The bug was fixed with commit e344854a73d9a5143bbd5b6988d5d56c538f9d92.
NuGet Packages and a release will be available soon.
You can apply this patch in the meantime by updating the following files from source:
- SharedStringReader.cs
- XlsxReader.cs
- AssemblyInfo.cs

Can you give me a quick feedback whether this fix resolved your issue?

Thank you for the report and your feedback in advance,
Raphael

**Comment by rabanti-github** [comment] 2019-12-01 19:06
NuGet Package and the release 1.3.4 are available.
Please reopen this issue, if something is not working as expected.
Thank you again for the contribution,

Raphael

**Closed by rabanti-github** 2019-12-01 19:06 UTC
Labels: bug

**Comment by rabanti-github** [comment] 2019-12-02 10:54
@Leonetienne It should now also be possible to insert empty values instead of a placeholder like EMPTY_STRING

**Comment by Leonetienne** [comment] 2019-12-04 13:54
Great! Thanks
