### ISSUE TITLE
Problem when creating XLSX file with more then 677 columns

### ISSUE THREAD

**Issue by karkal666** [rabanti-github/NanoXLSX#70] opened 2024-11-22 09:43 UTC
**Bug description**
When creating a XLSX file with more then 677 columns opening this file via Excel is raising a problem, some columns data are missing in XLSX in this case.

**Steps To Reproduce**
1. Create a workbook
2. In loop create for example 700 columns with some data. One row is enough
3. Corrupted file will be created

**Sample Code**
            var nowDateTime = DateTime.Now.ToString("dd.MM.yyyy");
            Workbook workbook = new Workbook(filePath, nowDateTime);

            for (int i = 0; i < 700; i++)
            {
                workbook.WS.Value(i.ToString());
            }
            workbook.Save();
            return;

**Expected behavior**
All columns should be fulfilled correctly.

**Screenshots and/or attachments**
![image](https://github.com/user-attachments/assets/04a0d8db-34cf-41a1-bde9-d08923967e85)
![image](https://github.com/user-attachments/assets/7e0e65ad-dd6f-41f5-a8e9-3ff766d0e038)
![image](https://github.com/user-attachments/assets/368bd7c7-00d2-4a61-9f25-ca0b733dc7f2)
![image](https://github.com/user-attachments/assets/8b1074fa-f657-4c7d-be2d-342c9f08488d)

**Environment (please complete the following information):**
- OS: Windows 10
- Your system locale 'pl-PL'
- Version of NanoXLSX 2.5.0

**Additional context**
Method for creating data does not matter, problem always occurs
Examples that have been used to test:
                workbook.WS.Value(i.ToString());
                workbook.CurrentWorksheet.AddCell(i.ToString(), adress);
                workbook.CurrentWorksheet.AddNextCell(i.ToString());

**Comment by rabanti-github** [comment] 2024-11-22 22:24
Hi,
Thanks for the report and the sample code.
The bug is confirmed, but I am currently still investigating the cause

**Comment by rabanti-github** [comment] 2024-11-22 23:05
The problem was identified and a fix is on the way.
Very odd that this bug was not discovered earlier, since it comes from the method that is determining the column letters - a very important and often used function... not thoroughly tested enough, as it looks. 🤷

**Comment by karkal666** [comment] 2024-11-23 05:59
Hi

Thanks for fast respond.
Yeah, when i found it i also could not believe that it is not working, so i created that very simole code to check it.
But from other side, it is not common to create xlsx with 800+ columns 😀

**Comment by rabanti-github** [comment] 2024-11-24 01:56
The problem was fixed in the new version v2.5.2. The Nuget package should be available in some minutes.
Thanks again for the report

**Closed by rabanti-github** 2024-11-24 01:56 UTC
Labels: bug, pending
