### ISSUE TITLE
Can't open Excel with custom cell style

### ISSUE THREAD

**Issue by CoolDixon** [rabanti-github/NanoXLSX#30] opened 2022-09-21 16:39 UTC
I'm using NanoXLSX v2.0.1 trying to open an excel with a custom cell style and get the exception

StyleException: The number '44' is not a valid custom format ID. Must be at least 164

![Screenshot 2022-09-21 at 18 30 43](https://user-images.githubusercontent.com/5981332/191561831-d81fc95b-e3ba-4dbd-93d8-97e7053ebc39.png)

 I just want to add a new Sheet (and delete an other), so I could live without loading the cell styles. Can you help me with this?

I attach the sample file.
[Test.xlsx](https://github.com/rabanti-github/NanoXLSX/files/9618673/Test.xlsx)

**Comment by rabanti-github** [comment] 2022-09-21 19:27
Hi,
Thanks for the report and the sample file. I will check it ASAP.

**Comment by rabanti-github** [comment] 2022-09-21 21:11
I have not considered the unaltered custom format codes. It looks like the enumeration of formats is split up into the normal (static) ones and the unaltered, customizable ones. Well, this would also explain the gaps in the enumeration.
I will provide a fix for this, hopefully the next few days.

**Comment by rabanti-github** [comment] 2022-09-25 21:37
Just a quick update:
Technically, the exception during loading is now fixed (but not published).
However, I encountered an odd string-escaping behavior of Excel on certain custom format codes. Im am currently figuring out how to unesacpe properly when loading a file

**Comment by rabanti-github** [comment] 2022-09-29 20:47
Hi,
The issue should be fixed now with v2.0.2.
The NuGet package should be available in a few minutes.
Thanks again for the report and please let me know if something is not working as expected.

**Comment by DixonDacya** [comment] 2022-09-30 07:21
Hi Rabanti,

Custom style error is gone, but now it complains about the color theme (same Test file as first post)
![Screenshot 2022-09-30 at 08 28 02](https://user-images.githubusercontent.com/114594828/193213950-c319c757-a0f6-4959-bea6-1d63333bd7df.png)

**Comment by rabanti-github** [comment] 2022-10-01 00:26
Hi,
I hope the issue is now fixed with v2.0.3. I missed last time to re-test with your file. Sorry about the inconvenience.
I had to look into the specs and will change some things in the next major version, when  it comes to ID and string values in styles.
The NuGet package should be available in some minutes.
Please let me know if something else is not working as expected.

**Comment by DixonDacya** [comment] 2022-10-02 10:44
It works like a charm now. Thanks a lot for your prompt support Rabanti ;)

**Closed** 2022-10-03 05:01 UTC
Labels: bug
